[package]
name = "groove-proc-macros"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
proc-macro-crate = "1.3"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
