[package]
name = "groove"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.12"
assert_approx_eq = "1.1.0"
clap = { version = "3.2.6", features = ["derive"] }
convert_case = "0.1.0"
cpal = "0.13.5"
crossbeam = "0.8"
hound = "3.4"
midir = "0.8.0"
midly = "0.5.2"
more-asserts = "0.1.0"
num-derive = "0.3"
num-traits = "0.2"
rhai = "1.8.0"
ringbuf = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sorted-vec = "0.8.0"
strum = "0.24.1"
strum_macros = "0.24.2"
