[package]
name = "groove"
version = "0.1.0"
authors = [ "Mike Tsao <mike@sowbug.com>" ]
edition = "2021"

[dependencies]
anyhow = "1.0.12"
assert_approx_eq = "1.1.0"
clap = { version = "3.2.6", features = ["derive"] }
convert_case = "0.1.0"
cpal = "0.13.5"
crossbeam = "0.8"
enum-primitive-derive = "0.2.2"
hound = "3.4"
iced = "0.4.2"
midir = "0.8.0"
midly = "0.5.2"
more-asserts = "0.1.0"
num-traits = "0.2"
plotters = "0.3.4"
ringbuf = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sorted-vec = "0.8.0"
spectrum-analyzer = "1.2.6"
strum = "0.24.1"
strum_macros = "0.24.2"

[[bin]]
name = "groove"
path = "src/bin/cli.rs"

[[bin]]
name = "groove-gui"
path = "src/bin/app.rs"

[lib]
name = "libgroove"
path = "src/lib.rs"
