[package]
name = "groove"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.12"
clap = { version = "3.2.6", features = ["derive"] }
cpal = "0.13.5"
hound = "3.4"
midly = "0.5.2"
ringbuf = "0.2"
