[package]
name = "groove"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.12"
assert_approx_eq = "1.1.0"
clap = { version = "3.2.6", features = ["derive"] }
cpal = "0.13.5"
crossbeam = "0.8"
hound = "3.4"
midly = "0.5.2"
more-asserts = "0.1.0"
num-derive = "0.3"
num-traits = "0.2"
ringbuf = "0.2"
sorted-vec = "0.8.0"
