[package]
name = "groove-entities"
version = "0.1.0"
edition = "2021"

[dependencies]
float-cmp = "0.9.0"
groove-core = { path = "../core" }
groove-macros = { path = "../macros" }
groove-toys = { path = "../toys" }
more-asserts = "0.3.1"
rand = "0.8.5"
strum = "0.24.1"
strum_macros = "0.24.2"
