# Copyright (c) 2023 Mike Tsao. All rights reserved.
[package]
name = "groove-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.12"
float-cmp = "0.9.0"
midly = "0.5.3"
more-asserts = "0.3.1"
