#!/usr/bin/env python3

import sys
import csv

def clean_keyword(s):
  return s.title.replace(" ", "").replace("(", "").replace(")", "").replace("-", "").replace("+", "").replace("_", "")

data = sys.stdin.readlines()
for line in csv.reader(data):
  print("%s = %d," % (clean_keyword(line[1]), int(line[0])))

for line in csv.reader(data):
  print("GeneralMidiProgram::%s => { // %d\npanic!();}" % (clean_keyword(line[1]), int(line[0]) + 1))
