#!/usr/bin/env python3

import sys
import csv

data = sys.stdin.readlines()
for line in csv.reader(data):
  print("%s = %d," % (line[1].title().replace(" ", "").replace("(", "_").replace(")", ""), int(line[0])))

for line in csv.reader(data):
  print("GeneralMidiProgram::%s => { // %d\npanic!();}" % (line[1].title().replace(" ", "").replace("(", "_").replace(")", "").replace("-", "").replace("+", ""), int(line[0]) + 1))
