#!/usr/bin/env python3
# 
# pip3 install MIDIUtil

from midiutil import MIDIFile

DIR = "midi_files"

degrees  = [60, 62, 64, 65, 67, 69, 71, 72]  # MIDI note number
track    = 0
channel  = 0
time     = 0    # In beats
duration = 0.8  # In beats
tempo    = 60   # In BPM
volume   = 100  # 0-127, as per the MIDI standard

def new_midi_file():
    # One track, defaults to format 1 (tempo track is created automatically)
    midi_file = MIDIFile(1)
    midi_file.addTempo(track, time, tempo)
    midi_file.addTimeSignature(track, 0, 4, 2, 24)
    return midi_file

def write_midi_file(f, name):
    with open("%s/%s" % (DIR, name), "wb") as output_file:
        f.writeFile(output_file)

f = new_midi_file()
for i, pitch in enumerate(degrees):
    f.addNote(track, channel, pitch, i, 1, volume)
write_midi_file(f, "major-scale.mid")

f = new_midi_file()
for i, pitch in enumerate(degrees):
    f.addNote(track, channel, pitch, i, 1.2, volume)
write_midi_file(f, "major-scale-overlapping.mid")

f = new_midi_file()
for i, pitch in enumerate(degrees):
    f.addNote(track, channel, pitch, i, 0.8, volume)
write_midi_file(f, "major-scale-spaced-notes.mid")

f = new_midi_file()
for ch in range(0, 4):
    for i, pitch in enumerate([60, 62, 64, 65, 67, 69, 71, 72]):
        f.addNote(track, ch, pitch + ch * 12, i, 1.0, volume)
write_midi_file(f, "multi-channel.mid")
