[package]
name = "groove-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.12"
app_dirs2 = "2.5.5"
async-std = "1.0"
strum = "0.24.1"
strum_macros = "0.24.2"
