#!/usr/bin/env python3

from os import listdir
from os.path import isfile, join
import subprocess

script_files = [f for f in listdir("./scripts/") if f.endswith(".yaml")]

subprocess.run(["cargo", "build", "--release"])
output_filenames = []
for filename in script_files:
    output_filename = "%s.wav" % filename
    output_filenames.append(output_filename)
    output_filename = "out/" + output_filename
    subprocess.run(["./target/release/groove-cli", "-q", "-y",
                   "scripts/%s" % filename, "-w", output_filename])

calculator_cmd = ["shasum"]
calculator_cmd.extend(output_filenames)
subprocess.run(calculator_cmd, cwd="./out")
