on: [push]

name: CI

jobs:
  build_and_test:
    name: Groove
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install alsa-sys dependency
        run: sudo apt -y install libasound2-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
