name: Release

on:
  release:
    types: [created]

jobs:
  release-x86_64:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu      # Most Linux machines
            os: ubuntu-20.04                      # TODO: change to 22.04 when 20.04 is EOL
          # - target: armv7-unknown-linux-gnueabihf # Raspberry Pi 3/4
          #   os: ubuntu-latest
          #   linker: gcc-arm-linux-gnueabihf
          # - target: aarch64-unknown-linux-gnu     # ARM Chromebooks
          #   os: ubuntu-latest
          #   linker: aarch64-linux-gnu-gcc
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt update
        if: startsWith(matrix.os, 'ubuntu')
      - run: sudo apt -y install pkg-config libfontconfig-dev librust-alsa-sys-dev
        if: startsWith(matrix.os, 'ubuntu')

      - uses: actions/checkout@master
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - run: cargo build --release
      - run: cargo test --release --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: groove-${{ matrix.target }}
          path: |
            target/release/groove-cli*
            target/release/groove-gui*
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: groove-gui,groove-cli
          include: README.md,LICENSE.txt,assets,projects
          leading_dir: true
          archive: groove-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
