name: Release

on:
  release:
    types: [created]

jobs:
  release-all:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04 # TODO: change to 22.04 when 20.04 is EOL
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: apt update
        run: sudo apt update
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install dependencies
        # also needed: build-essentials gcc cmake, but GitHub barfs on at least one of those
        run: sudo apt -y install pkg-config libfontconfig-dev librust-alsa-sys-dev
        if: startsWith(matrix.os, 'ubuntu')
      - name: Build
        run: cargo build --release --all
      - name: Run tests
        run: cargo test --release --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: groove-${{ matrix.target }}
          path: |
            target/release/groove-cli*
            target/release/groove-gui*
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: groove-gui,groove-cli
          include: README.md,LICENSE.txt,assets,projects
          leading_dir: true
          archive: groove-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
