name: Release

on:
  release:
    types: [created]

jobs:
  release-x86_64:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
        # Set up the build machine
      - name: Install Linux x86_64 build dependencies
        run: |
          sudo apt -qq update
          sudo apt -y install pkg-config libfontconfig-dev librust-alsa-sys-dev gcc
        if: startsWith(matrix.os, 'ubuntu')

      - name: Install latest Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          target: ${{ matrix.target }}
      - name: Install cargo components for .deb
        run: cargo install cargo-deb
        if: startsWith(matrix.os, 'ubuntu')
      - name: Install cargo components for .msi
        run: cargo install cargo-wix
        if: startsWith(matrix.os, 'windows')
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

        # Get the source
      - name: Check out source
        uses: actions/checkout@v3

        # Build and test
      - name: Set version environment variables
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
        # https://stackoverflow.com/a/65972328/344467
        run: |
          echo 'GIT_DESCRIBE<<QQEOFQQ' >> $GITHUB_ENV
          git describe --tags          >> $GITHUB_ENV
          echo 'QQEOFQQ'               >> $GITHUB_ENV
      - name: Build release
        run: cargo build --workspace --release --target ${{ matrix.target }}
      - name: Test release
        run: cargo test  --workspace --release --target ${{ matrix.target }}
      - name: Build .deb
        run: cargo deb --target ${{ matrix.target }} --no-build
        if: startsWith(matrix.os, 'ubuntu')
      - name: Build .msi
        run: cargo wix -v --nocapture -o .
        if: startsWith(matrix.os, 'windows')

        # Upload build products
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: groove-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/groove-cli*
            target/${{ matrix.target }}/release/groove-gui*
            perf-output.txt
      - name: Upload binaries
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: groove-gui,groove-cli
          include: README.md,LICENSE.txt,assets,projects
          leading_dir: true
          archive: groove-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload installer
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/**/*.msi
            target/**/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}

  release-cross:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-unknown-linux-gnu # ARM Chromebooks & 64-bit RPi
          - armv7-unknown-linux-gnueabihf # Raspberry Pi 3/4 32-bit
          # - riscv64gc-unknown-linux-gnu # The future!
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - name: Install cargo components for .deb
        run: cargo install cargo-deb
      - name: Set version environment variables
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
        # https://stackoverflow.com/a/65972328/344467
        run: |
          echo 'GIT_DESCRIBE<<QQEOFQQ' >> $GITHUB_ENV
          git describe --tags          >> $GITHUB_ENV
          echo 'QQEOFQQ'               >> $GITHUB_ENV
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Build installer
        run: cargo deb --target ${{ matrix.target }} --no-build --no-strip
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: groove-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/groove-cli*
            target/${{ matrix.target }}/release/groove-gui*
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: groove-gui,groove-cli
          include: README.md,LICENSE.txt,assets,projects
          target: ${{ matrix.target }}
          leading_dir: true
          archive: groove-$tag-$target
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload installer
        uses: softprops/action-gh-release@v1
        with:
          files: target/**/*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
