name: Release

on:
  release:
    types: [created]

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apt update
        run: sudo apt update
      - name: Install dependencies
        # also needed: build-essentials gcc cmake, but GitHub barfs on at least one of those
        run: sudo apt -y install pkg-config libfontconfig-dev librust-alsa-sys-dev
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --release --all
      - name: Run tests
        run: cargo test --verbose
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: groove-gui,groove-cli
          archive: groove-$target
          token: ${{ secrets.GITHUB_TOKEN }}
